# -*- coding: utf-8 -*-
"""Hourly Acttivity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13gcWDnlXAq-cfenBfshQiPrxrckhb5Ah
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Hourly_Calories_df = pd.read_csv('/content/drive/MyDrive/hourlyCalories_merged.csv')
Hourly_Intensities_df = pd.read_csv('/content/drive/MyDrive/hourlyIntensities_merged.csv')
Hourly_Steps_df = pd.read_csv('/content/drive/MyDrive/hourlySteps_merged.csv')
Hourly_Calories_df.head()

Hourly_Intensities_df.head()

Hourly_Steps_df.head()

#Merge the dataset using common columns
merged_df = pd.merge(Hourly_Calories_df, Hourly_Intensities_df, on=["Id","ActivityHour"])
Hourly_Activity_merged_df = pd.merge(merged_df, Hourly_Steps_df, on=["Id","ActivityHour"])

#Display the merged dataset
Hourly_Activity_merged_df.head()

Hourly_Activity_merged_df['ActivityHour'] = pd.to_datetime(Hourly_Activity_merged_df['ActivityHour'])

Hourly_Activity_merged_df.shape

Hourly_Activity_merged_df.info()

Hourly_Activity_merged_df.describe()

# check out missing values in the dataset
missing_values_count = Hourly_Activity_merged_df.isnull().sum()

# look at the # of missing points in all columns
missing_values_count[:]

Hourly_Activity_merged_df['ActivityHour'].value_counts()

Hourly_Activity_merged_df['HourlyDate'] = [d.date() for d in Hourly_Activity_merged_df['ActivityHour']]
Hourly_Activity_merged_df['HourlyTime'] = [d.time() for d in Hourly_Activity_merged_df['ActivityHour']]

Hourly_Activity_merged_df.head()

# Drop column 'ActivityHour'
Hourly_Activity_merged_df = Hourly_Activity_merged_df.drop('ActivityHour', axis=1)
Hourly_Activity_merged_df.head()

# Convert ActivityDate from object to datetime64type
Hourly_Activity_merged_df["HourlyDate"] = pd.to_datetime(Hourly_Activity_merged_df["HourlyDate"], format = "%m/%d/%Y")

Hourly_Activity_merged_df.HourlyDate.head(5)

"""**Install Pandas Profiling**"""

pip install pandas-profiling

import pandas as pd
from ydata_profiling import ProfileReport

# Convert datetime.date objects to pandas Timestamps
for col in Hourly_Activity_merged_df.columns:
    if Hourly_Activity_merged_df[col].dtype == 'object':  # Check if the column contains object dtype (could be datetime.date)
        try:
            Hourly_Activity_merged_df[col] = pd.to_datetime(Hourly_Activity_merged_df[col])
        except:
            pass  # If conversion fails, it's likely not a date column

# Now create the profile report
Profile = ProfileReport(Hourly_Activity_merged_df, title="Hourly Activity Reports", html={'style':{'full_width':True}})

Profile

#Save the merged dataset to a new CSV file
Hourly_Activity_merged_df.to_csv('Hourly_Activity_merged.csv', index=False)

