# -*- coding: utf-8 -*-
"""Sleep_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14MqswUb1FQ8gUNPcKR7KInZ2g75MkSAz
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Minute_Sleep_merged = pd.read_csv('/content/drive/MyDrive/minuteSleep_merged.csv')
Sleep_Day_merged = pd.read_csv('/content/drive/MyDrive/sleepDay_merged.csv')

Minute_Sleep_merged.head()

Sleep_Day_merged.head()

#Merge the dataset using a common key , such as 'Id' or 'Date' depending on your data
Sleep_merged = pd.merge(Minute_Sleep_merged, Sleep_Day_merged, on='Id' , how = 'inner')

Sleep_merged.head()

Sleep_merged.info()

#Check null values
Sleep_merged.isnull().sum()

#Check Duplicate Values
Sleep_merged.duplicated().sum()

# Convert date and format
Sleep_merged['date'] = pd.to_datetime(Sleep_merged['date'])
Sleep_merged['date'] = pd.to_datetime(Sleep_merged['date']).dt.strftime('%m/%d/%Y')
Sleep_merged['date'] = Sleep_merged['date'].str.replace('/', '-')

Sleep_merged.head()

# Convert SleepDay and format
Sleep_merged['SleepDay'] = pd.to_datetime(Sleep_merged['SleepDay'])
Sleep_merged['SleepDay'] = pd.to_datetime(Sleep_merged['SleepDay']).dt.strftime('%m/%d/%Y')
Sleep_merged['SleepDay'] = Sleep_merged['SleepDay'].str.replace('/', '-')

Sleep_merged.head()

Sleep_merged.describe()

"""# Install Pandas Profiling"""

pip install pandas-profiling

import pandas as pd
from ydata_profiling import ProfileReport

# Now create the profile report
Profile = ProfileReport(Sleep_merged, title="Sleep Activity Reports", html={'style':{'full_width':True}})

Profile

#Save the merged dataset to a new CSV file
Sleep_merged.to_csv('Sleep_merged.csv', index=False)

